const page1CardData = [
    {
      title: "Dynamic Data sets provided by Caleus Framework",
      img: "https://media.giphy.com/media/DyQrKMpqkAhNHZ1iWe/giphy.gif?cid=82a1493boi0qtei6fk4053oolyjicm28pwm83lghonanq8dv&ep=v1_gifs_trending&rid=giphy.gif&ct=g",
      text: "This card is dynamically generated by Caleus Framework. You can add more data sets to this page by adding them to the page1CardData.js file.",
    },
    {
      title: "Caleus Framework is a React-based framework leveraging GraphQL",
      img: "https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExOWl4em1oaXhjbGFrajV1cHQyajhodWhiNzBmNmRoenpzOXVqejN2byZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/JWuBH9rCO2uZuHBFpm/giphy.gif",
      text: "The content of page1 is managed in utils/page1CardData.js, limiting the need for hardcoded data in the component.",
    },
    {
      title: "The dynamic data solution is designed to be extensible",
      img: "https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExNm1wNzVqYnc5bnBxbTUxM2lxamd0cGgweGhnengzbHk1YW93NTQxZCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/UEGwYCVTBFa9tJEf66/giphy.gif",
      text: "this solution reduces the need for hardcoded and data stored on the database making a more efficient light-weight application.",
    },
  ];

  export default page1CardData;